import cv2
import os
import ntpath as path
import argparse

from utils import progress_bar

parser = argparse.ArgumentParser(
    description='Crops images generated by `generate_visuals.py`'
)
parser.add_argument('image_folder', action='store',
                    help='should be GTAV_program\\drivedata\\imvid')
args = parser.parse_args()

if not path.isdir(args.image_folder):
    print('the specified image folder does not exist')
    print('please run `generate_visuals.py` first')
    exit(1)

dst_folder = path.join(args.image_folder, '..', 'crop')

# clear out dst_folder if already exists
if not path.exists(dst_folder):
    os.mkdir(dst_folder)
else:
    filelist = os.listdir(dst_folder)
    for file in filelist:
        filepath = path.join(dst_folder, file)
        filepath = path.join(args.image_folder, file)
        name, ext = path.splitext(filepath)
        if ext == '.jpg':
            os.remove(filepath)

filelist = os.listdir(args.image_folder)
num_files = len(filelist)

for i, file in enumerate(filelist):
    progress_bar(i, num_files)
    filepath = path.join(args.image_folder, file)
    name, ext = path.splitext(filepath)
    if ext == '.jpg':
        img = cv2.imread(filepath)
        crop_img = img[320:720, 440:840]
        cv2.imwrite(
            path.join(dst_folder, f'{str(i).zfill(9)}_img.jpg'), crop_img)

print(f'successfully cropped images, stored in {dst_folder}')
