DARKNET_DIR=$1
PATH_TO_WEIGHTS=$2
IMG_DIR=$3
PATH_TO_OBJDATA=$4
PATH_TO_CFG=$5
LIST=files.txt

ls -d $IMG_DIR/*.jpg > $LIST
$DARKNET_DIR/darknet detector active $PATH_TO_OBJDATA $PATH_TO_CFG $PATH_TO_WEIGHTS < $LIST
rm $LIST
